### ISSUE TITLE
Misspelled range check [was: "useless condition"]

### ISSUE THREAD

**Issue by maddin200** [deepmind/lab2d#1]
dmlab2d/system/image/lua_image.cc line 517
Code:
  if (!(0 >= hue_prime_ && hue_prime_ < 6.0)) {  // <- probably hue_prime_ >= 0.0
      hue_prime_ -= 6.0 * std::floor(hue_prime_ / 6.0);
    }

**Comment by charlesbeattie** [comment]
Can you explain why the condition is useless?
This (branch predicted) condition saves doing the floor and division calculation when not necessary.

**Comment by maddin200** [comment]
if  0 >= hue_prime_ then automatically hue_prime_ is smaller than 6.0

**Comment by charlesbeattie** [comment]
Good Spot! is should be:
if (!(0 <= hue_prime_ && hue_prime_ < 6.0)) 

I'll update.

**Comment by tkoeppe** [comment]
Fixed by 2261b939ebd574505346accd09ce5b9e30398998, thank you very much for reporting!
