### ISSUE TITLE
Add in hidden_reward for safety/control/ethics research

### ISSUE THREAD

**Issue by jifflund** [deepmind/lab2d#10]
Lab2D and Melting Pot should support outputting a hidden_reward as part of the step method to enable safety/control/ethics research.  The hidden_reward output will be basically the same as the hidden_reward supported in https://github.com/deepmind/ai-safety-gridworlds.

If there is a better way to do hidden_rewards than the approach implemented in the ai-saftey-gridworlds, please add suggestions below to be discussed.

Next step:  I think this means changes are needed to Lab2D, Melting Pot and also dm_env and will look into what specific changes are needed.

**Comment by charlesbeattie** [comment]
Hi, the reward returned by step is only used for simplified single player RL environments and for any other types of data I would suggest using additional observations. This will prevent the need for changing Lab2D and dm_env. You can see this being done with the the multiplayer example environment clean_up here: https://github.com/deepmind/lab2d/blob/f634c378d428dd19e8b154aa5b590d33f42438bf/dmlab2d/lib/game_scripts/levels/clean_up/avatar.lua#L182.

**Comment by jifflund** [comment]
@charlesbeattie ,  👍  Thanks for the reference.  This looks good and I'll give it a try.   Will close this issue for now.
