### ISSUE TITLE
Build of a Python package possible?

### ISSUE THREAD

**Issue by Robert-Held** [deepmind/lab2d#11]
Is it possible to build a Pip-installable Python package from Lab2D?

I need to run Lab2D within another Python script but found no solution on how to build and import it successfully. (I may have overlooked something, though.) The [Lab repo](https://github.com/deepmind/lab) has [prepared a process](https://github.com/deepmind/lab/tree/master/python/pip_package) for this, so maybe this is possible with Lab2D, too?

Thanks!

**Comment by tkoeppe** [comment]
I would hope so! Let me take a look and remind myself where we are. @charlesbeattie, any thoughts?

**Comment by tkoeppe** [comment]
Yes, there are Bazel build rules to make wheels: https://github.com/deepmind/lab2d/blob/main/dmlab2d/BUILD#L105-L135

We even attached a few prebuilt wheels to the [last release tag](https://github.com/deepmind/lab2d/releases/tag/release_candidate_2021-07-13).

This is much easier than what we did in Lab, and I've been meaning to modernize Lab's process, too.

**Comment by Robert-Held** [comment]
Thanks! This helped a lot.

So, for a quick rundown to build with an own Level:

1. Create the level `foo` with all necessary files in `dmlab2d/lib/game_scripts/levels/foo`.
2. Add the level to the BUILD file located in `dmlab2d/lib/`:
```
cc_library(
    name = "dmlab2d",
    # ...
    data = [
        ":game_scripts",
        # ...
        "//dmlab2d/lib/game_scripts/levels/foo",
    ],
    # ...
```
3. Bazel-build the package: `$ bazel build //dmlab2d:dmlab2d_wheel`
4. in a Python virtualenv: `pip install <my-lab2d-src-dir>/bazel-bin/dmlab2d/dm-lab2d-1.0-xxxxxxx.whl`
5. And in my Python file:
```python
import dmlab2d
from dmlab2d import runfiles_helper

# within main():
    settings = {
        'levelName': 'foo'
    }
    lab2d = dmlab2d.Lab2d(runfiles_helper.find(), settings)
```

This is how far I've come today. I'll continue trying to make it work tomorrow. Is this the correct approach so far?

**Comment by tkoeppe** [comment]
If you only want to add new levels, you probably don't need to rebuild wheels, You can just add them to the existing assets directory (e.g. via https://github.com/deepmind/lab2d/blob/5ab5484f50cc414d9e0117f9bbf7c72999903e53/dmlab2d/runfiles_helper.py#L47-L58).

**Comment by charlesbeattie** [comment]
There is actually a customisation point via settings where you can specify a `"levelDirectory"`. Then specify the full path to the Lua files. You will not need to rebuild between edits.

You can see how meltingpot does this here: https://github.com/deepmind/meltingpot/blob/main/meltingpot/python/configs/substrates/clean_up.py#L553-L571

**Comment by Robert-Held** [comment]
Yes, that's exactly what I needed. Storing and loading the level went over flawlessly. ❤️ 
Thank you! That was a big help.
