### ISSUE TITLE
Run in pure python command without bazel

### ISSUE THREAD

**Issue by Theohhhu** [deepmind/lab2d#13]
Hi, guys,
I was stuck in running the command
> bazel run -c opt dmlab2d/python:random_agent -- --level_name=clean_up

With a error prompt
> ERROR: --flag_alias is experimental. Set --experimental_enable_flag_alias to true to make use of it. Detected aliases: --flag_alias=lua_version=//dmlab2d/lib/lua:lua_version

I am not familiar with bazel,
is there any solution I can run a pure python command to train my agent with out **bazel run -c opt** ?

It would be really convenient cuz I need to using debug mode in Pycharm to add and test my own code based on lab2d.

Thanks.

Edit:

Pure python run on random-agent.py will cause error:
> ModuleNotFoundError: No module named 'dmlab2d.dmlab2d_pybind'

**Comment by tkoeppe** [comment]
Oh, which Bazel version are you using? Could you update maybe? `--flag_alias` should be supported: https://docs.bazel.build/versions/main/command-line-reference.html#flag--flag_alias

Alternatively, just remove the [offending flag](https://github.com/deepmind/lab2d/blob/a983c21be6ecb25c2117cef6f4af6c956420379e/.bazelrc#L3) from `.bazelrc`; it shouldn't be needed if you don't want to switch Lua versions.

**Comment by Theohhhu** [comment]
Currently i am using bazel 3.7.2

By removing the offending flag from .bazelrc, the --flag_alias related error is gone.

running the command
> bazel run -c opt dmlab2d/python:random_agent -- --level_name=clean_up

it start with loading the package and then add addtional directories like bazel-bin bazel-lab2d to the working directory.

and then the error come up with
> ERROR: /home/hsy/PycharmProjects/lab2d/dmlab2d/lib/env_lua_api/BUILD:5:11: C++ compilation of rule '//dmlab2d/lib/env_lua_api:env_lua_api' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 60 argument(s) skipped)

> Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 60 argument(s) skipped)

> Use --sandbox_debug to see verbose messages from the sandbox
dmlab2d/lib/env_lua_api/env_lua_api.cc:20:10: fatal error: filesystem: No such file or directory

I check the dmlab2d/lib/env_lua_api/env_lua_api.cc and it exits.

What's the problem?

**Comment by tkoeppe** [comment]
Does your compiler provide the `<filesystem>` header? This is part of C++17, which is required for Lab2D.

**Comment by GoingMyWay** [comment]
Hi, I was trying to build the wheel file, however, it failed by outputting the following error

```
$ bazel build //dmlab2d:dmlab2d_wheel
loading:
Loading: 0 packages loaded
DEBUG: Rule 'bazel_skylib' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "16d40a28a09bf72fe915c6ecf612bf5b8578918b9784b1e0716f606692c44b26"
DEBUG: Repository bazel_skylib instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_qiuwei/d8a610d93c48820c8f4362a60f2b7dca/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
Analyzing: target //dmlab2d:dmlab2d_wheel (0 packages loaded, 0 targets configured)
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "ad1b6cdf525b1a7c50b27f2df32863d30d1cce12f855b5e038e33650af5021d8"
DEBUG: Repository rules_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_qiuwei/d8a610d93c48820c8f4362a60f2b7dca/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'dm_env_archive' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "64e62362f5b0f27edccc54b9d9a41f450436be59cf1844e8fe74f934eda35825"
DEBUG: Repository dm_env_archive instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_qiuwei/d8a610d93c48820c8f4362a60f2b7dca/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3839996049629e6377abdfd04681ddeeb0cc3db13b9d2ff81bf46700cb4529f7"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_qiuwei/d8a610d93c48820c8f4362a60f2b7dca/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'pybind11_archive' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "7679b3251d229780ff66c0a2a09bcb7e898d8ba641846b7fc8b864828e70d553"
DEBUG: Repository pybind11_archive instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_qiuwei/d8a610d93c48820c8f4362a60f2b7dca/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "16fe485f64d1ae98dc47bbfadd0e83c0548ecfb44808ae2f36bf701144224bc7"
DEBUG: Repository com_google_absl instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_qiuwei/d8a610d93c48820c8f4362a60f2b7dca/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://mirror.bazel.build/github.com/glennrp/libpng/archive/v1.6.37.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'funcsigs_archive' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a7bb0f2cf3a3fd1ab2732cb49eba4252c2af4240442415b4abce3b87022a8f50"
DEBUG: Repository funcsigs_archive instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_qiuwei/d8a610d93c48820c8f4362a60f2b7dca/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //dmlab2d:dmlab2d_wheel (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 8] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
ERROR: /private/var/tmp/_bazel_goingmyway/d8a610d93c48820c8f4362a60f2b7dca/external/luajit_archive/BUILD.bazel:4:11: C++ compilation of rule '@luajit_archive//:luajit' failed (Exit 1) sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_qiuwei/d8a610d93c48820c8f4362a60f2b7dca/sandbox/darwin-sandbox/459/execroot/org_deepmind_lab2d && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/qiuwei/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/var/folders/mk/ghr8_pm142j03yt6ch8tjbmhk9y311/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_qiuwei/d8a610d93c48820c8f4362a60f2b7dca/sandbox/darwin-sandbox/459/sandbox.sb /var/tmp/_bazel_qiuwei/install/44090000910a11db7c3520e6fcb2c4fe/process-wrapper '--timeout=0' '--kill_delay=15' external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -MD -MF bazel-out/darwin-fastbuild/bin/external/luajit_archive/_objs/luajit/lj_vm.pic.d -fPIC -iquote external/luajit_archive -iquote bazel-out/darwin-fastbuild/bin/external/luajit_archive -isystem external/luajit_archive/src -isystem bazel-out/darwin-fastbuild/bin/external/luajit_archive/src -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c bazel-out/darwin-fastbuild/bin/external/luajit_archive/lj_vm.S -o bazel-out/darwin-fastbuild/bin/external/luajit_archive/_objs/luajit/lj_vm.pic.o)
bazel-out/darwin-fastbuild/bin/external/luajit_archive/lj_vm.S:6:2: error: unknown directive
 .hidden lj_vm_asm_begin
 ^
bazel-out/darwin-fastbuild/bin/external/luajit_archive/lj_vm.S:7:2: error: unknown directive
 .type lj_vm_asm_begin, @object
 ^
bazel-out/darwin-fastbuild/bin/external/luajit_archive/lj_vm.S:8:2: error: unknown directive
 .size lj_vm_asm_begin, 0

bazel-out/darwin-fastbuild/bin/external/luajit_archive/lj_vm.S:2523:2: error: unknown directive
 .hidden lj_vm_ffi_call
 ^
bazel-out/darwin-fastbuild/bin/external/luajit_archive/lj_vm.S:2524:2: error: unknown directive
 .type lj_vm_ffi_call, @function
 ^
bazel-out/darwin-fastbuild/bin/external/luajit_archive/lj_vm.S:2525:2: error: unknown directive
 .size lj_vm_ffi_call, 160
 ^
bazel-out/darwin-fastbuild/bin/external/luajit_archive/lj_vm.S:2538:20: error: unexpected token in '.section' directive
 .section .note.GNU-stack,"",@progbits
                   ^
bazel-out/darwin-fastbuild/bin/external/luajit_archive/lj_vm.S:2541:11: error: mach-o section specifier uses an unknown section type
 .section .debug_frame,"",@progbits
          ^
bazel-out/darwin-fastbuild/bin/external/luajit_archive/lj_vm.S:2595:11: error: mach-o section specifier uses an unknown section type
 .section .eh_frame,"a",@progbits
          ^
Target //dmlab2d:dmlab2d_wheel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.733s, Critical Path: 0.47s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I deleted the `build --flag_alias=lua_version=//dmlab2d/lib/lua:lua_version` and `build:lua5_2 --lua_version=lua5_2`. The current lua version is 5.4, the version of luajit is 2.0.5. Python3.9 and macos. bazel 3.2.0.

Lab2d is a cool library and could you please add more content so that users can build the wheel and customize the environments on their own?

**Comment by tkoeppe** [comment]
@GoingMyWay: Are you running this on Linux or on MacOS? LuaJit does not work on MacOS, use one of the other Lua versions there (see the precommit checks on GitHub for example builds).

**Comment by tkoeppe** [comment]
> Lab2d is a cool library and could you please add more content so that users can build the wheel and customize the environments on their own?

Do you have any concrete suggestions? You can already build the wheel file with Bazel, and you can load your own level scripts, too. What else did you have in mind?

**Comment by GoingMyWay** [comment]
> @GoingMyWay: Are you running this on Linux or on MacOS? LuaJit does not work on MacOS, use one of the other Lua versions there (see the precommit checks on GitHub for example builds).

Hi, @tkoeppe  My machine is MacBook Pro, the os is macOS Monterey.  Where can I find the `precommit checks on GitHub for example builds`?

**Comment by GoingMyWay** [comment]
> > Lab2d is a cool library and could you please add more content so that users can build the wheel and customize the environments on their own?
> 
> Do you have any concrete suggestions? You can already build the wheel file with Bazel, and you can load your own level scripts, too. What else did you have in mind?

Hi, @tkoeppe, many RL researchers do not have solid engineering experiences to use many tools. DeepMind has created many awesome tools for RL research and the community benefit a lot. To improve the user experience, it would be great to specify more installation details (add how to install from the source and install from wheel file in the README.md ) and list workarounds for potential bugs and errors. I understand it will take some time. It is my humble suggestion.

**Comment by tkoeppe** [comment]
The precommit checks are here, https://github.com/deepmind/lab2d/blob/main/.github/workflows/precommit.yml, and you can just click on any green tick mark in the commit history to see the actual run logs. You want something like `--config=lua5_2` or `--config=lua5_1` on MacOS, and the meaning of those configs is defined in the bazelrc file https://github.com/deepmind/lab2d/blob/main/.bazelrc.

**Comment by tkoeppe** [comment]
Pull requests are welcome if you have some concrete documentation suggestions :-) I'd probably prefer links to external documentation (e.g. Bazel) over duplicating something that talks about external systems -- any such "end to end" documentation would need active review and maintenance to stay relevant and accurate. I could imagine hosting some "community contributed guides", though.

@charlesbeattie: any thoughts?

**Comment by GoingMyWay** [comment]
> 

@tkoeppe Thanks for your time and effort in maintaining Lab2d. It would be very nice if your team welcomes PRs for the docs. I am using Lab2D in my research and hopefully, I will add some content to the document from an ordinary RL researcher's perspective and expertise on using Lab2d.

**Comment by tkoeppe** [comment]
Thanks! Yes, I'd be interested in taking a look. Maybe start by describing what you have in mind roughly in an Issue, just so we can avoid getting too far into it too early.
