### ISSUE TITLE
Error installing from wheel

### ISSUE THREAD

**Issue by jkterry1** [deepmind/lab2d#16]
I'm using a Linux system with python 3.7 on GCP deep learning image for GPUs, here's the system info:

```
jkterry0@instance-3:~$ python3
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0] on linux
```

```
jkterry0@instance-3:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
jkterry0@instance-3:~$ pip -V
pip 22.0.3 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
Codename:       buster
```

```
jkterry0@instance-3:~$ pip -V
pip 22.0.3 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
```

However, when I try to install the corresponding wheel image this happens and I have absolutely no idea why:

```
jkterry0@instance-3:~$ pip install [https://github.com/deepmind/lab2d/releases/download/release_c](https://github.com/deepmind/lab2d/releases/download/release_candidate_2021-07-13/dmlab2d-1.0-cp37-cp37m-manylinux_2_31_x86_64.whl)
[andidate_2021-07-13/dmlab2d-1.0-cp37-cp37m-manylinux_2_31_x86_64.whl](https://github.com/deepmind/lab2d/releases/download/release_candidate_2021-07-13/dmlab2d-1.0-cp37-cp37m-manylinux_2_31_x86_64.whl)
ERROR: dmlab2d-1.0-cp37-cp37m-manylinux_2_31_x86_64.whl is not a supported wheel on this platfor
m.
```

**Comment by tkoeppe** [comment]
What is your glibc version, out of curiosity?

You could also try and use the unversioned wheel that doesn't enforce any platform constraints (https://github.com/deepmind/lab2d/blob/51e45d3a8b807786ec13eb68f6aa75477b12db31/dmlab2d/BUILD#L116-L131).

**Comment by jkterry1** [comment]
glibc:

```
jkterry0@instance-3:~$ ldd --version
ldd (Debian GLIBC 2.28-10) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Forgive my ignorance, but what would the full command to build and install the unversioned wheel from that be?

**Comment by tkoeppe** [comment]
That might be the problem? The wheel seems to require glibc 2.31 (Not sure why! That's what Python says.)

The unversioned wheel is `:dmlab2d_wheel_local`, instead of `:dmlab2d_wheel`.

Oh wait, you're not building anything locally, you're just downloading this from our release page? Then yes, I suppose our wheels require glibc >= 2.31, sorry about that. We just use the current github runner to build them.

**Comment by tkoeppe** [comment]
I suppose we should add some documentation on how to build the wheels, @charlesbeattie.

```
bazel build -c opt //dmlab2d:dmlab2d_wheel
bazel build -c opt //dmlab2d:dmlab2d_wheel_local
```

**Comment by jkterry1** [comment]
@tkoeppe I ran `bazel build -c opt //dmlab2d:dmlab2d_wheel_local` on my system and it worked without error, but what's the command to install into python given the bazel build?

**Comment by tkoeppe** [comment]
You use `pip`, and the resulting wheel file name should be printed ads the result of running bazel.
