### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/lab2d#2]
Hi, will you provide Dockerfile?

**Comment by RacingTadpole** [comment]
In case this helps, while I was exploring ways to work around issue #3, I developed the following Dockerfile that works on MacOS up to the point of connecting a display to pygame, although it fails at that point with `No suitable video driver found`. Neither [this blog](https://opeonikute.dev/posts/running-pygame-in-a-docker-container-macos) nor [this one](https://blog.gladis.org/2017/2/run_pygame_for_python3_in_docker/) helped - it looks like this could be a pygame/macOS issue.

Before using this you need to copy your python header files into a local `python3.8/` directory; you can find them on MacOS using
```
python3.8-config --includes
```
Eg.
```
cp -R /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 .
```
(I couldn't immediately find how to install these more directly for python 3.8; headers for 3.7 are available though, with `RUN apt-get update && apt-get install python3.7-dev`.)

Also I've used [pipenv](https://pipenv.pypa.io/en/latest/) to install `numpy` and `pygame` via a `Pipfile`, but using `pip` and `requirements.txt` would be quicker here.

```
FROM python:3.8 AS base

WORKDIR /app

RUN curl -sL https://deb.nodesource.com/setup_12.x  | bash - && \
    apt-get -y install nodejs && \
    npm install -g @bazel/bazelisk && \
    bazel

RUN pip install pipenv
COPY Pipfile Pipfile.lock  /app/
RUN pipenv install --system --deploy

COPY . .
COPY python3.8/ /usr/include/

RUN bazel run -c opt dmlab2d/python:random_agent -- --level_name=clean_up
```

**Comment by tkoeppe** [comment]
@RacingTadpole: I put some effort into MacOS support (esp. see the `beta` branch), could you kindly take a look and see if that helps at all?

**Comment by RacingTadpole** [comment]
Thanks! I tried pushing a commit to my own fork of this repo to see the precommit [changes](https://github.com/deepmind/lab2d/commit/f6b8774035a47e49f9e74dc9439b80266f2ee0e5#diff-05facd54dc227d5ba65b60508aee3b8ea42a3a715cbfec5a3f60b0493d40c3d5) in action, but i couldn't see anything happening - how should I test that out?

Re the changes to bazel/python.BUILD - on my Mac anyway `/usr/local/Frameworks/Python.framework/Versions/` exists but is empty. `/Library/Frameworks/Python.framework/Versions` has both `3.8` and `Current` which is a link to `3.8`. (If `Current` exists for everyone that would nicely abstract away from the version number?)

It would be worth documenting the need for lua5.2 instead of luajit for Mac too.

**Comment by tkoeppe** [comment]
> Thanks! I tried pushing a commit to my own fork of this repo to see the precommit [changes](https://github.com/deepmind/lab2d/commit/f6b8774035a47e49f9e74dc9439b80266f2ee0e5#diff-05facd54dc227d5ba65b60508aee3b8ea42a3a715cbfec5a3f60b0493d40c3d5) in action, but i couldn't see anything happening - how should I test that out?

You mean on GitHub? Have you already got actions set up? I think you need to do that explicitly, I think if you just fork a repo, you don't get its actions enabled for your fork (but I'm not sure about that).

> Re the changes to bazel/python.BUILD - on my Mac anyway `/usr/local/Frameworks/Python.framework/Versions/` exists but is empty. `/Library/Frameworks/Python.framework/Versions` has both `3.8` and `Current` which is a link to `3.8`. (If `Current` exists for everyone that would nicely abstract away from the version number?)

Interesting, maybe? I was wondering if that would work properly with Py2/Py3 selection, but I suppose Py2 is frozen at 2.7 at this point, so maybe that's a robust assumption.

> It would be worth documenting the need for lua5.2 instead of luajit for Mac too.

Yes, good idea. If we pull that branch onto the main branch, I should make a note.

**Comment by tkoeppe** [comment]
Some updates:

* We now have a build rule to make Python Wheel files.
* We now compute the Python include paths automatically, based on the actual local Python interpreter you're using, so there's no longer any need to edit any BUILD files to match the local setup.
