### ISSUE TITLE
Wanted: LuaJit update

### ISSUE THREAD

**Issue by tkoeppe** [deepmind/lab2d#27]
We are building LuaJit from source, and we have pinned the source to the latest "released" version, which is 2.1.0-beta from 2017: https://github.com/deepmind/lab2d/blob/ff8853a3ba4c181adccfff2ce6aeae5635f9bba5/WORKSPACE#L102-L108

Unfortunately there doesn't seem to be any indication that there will be another stable release any time soon, but it would nonetheless be good if we could update our dependency to a more modern version. It would probably be OK to just use the `2.1` branch, which is the active development trunk. A major motivation for the update is that a it's hard to support MacOS without the update. (The 2017 version requires working in the first 4GB of address space, which is an obsolescent feature of MacOS that is deprecated in MacOS 13. More recent versions of LuaJit no longer have this limiting requirement.)

Making the update requires, apart from updating the `WORKSPACE` file, updating [`bazel/luajit.BUILD`](https://github.com/deepmind/lab2d/blob/main/bazel/luajit.BUILD) with the list of source files, and perhaps with some new macro defines for the build; this would have to be figured out. Presumably it would be a good start to compare the changes in the `Makefile` between versions.

**Comment by tkoeppe** [comment]
Done by 02d4d547d66887a9501caaa8522bea50a5b8aef6.

**Comment by ashok-arora** [comment]
Oh wow, thank you so much! ✨
