### ISSUE TITLE
Ubuntu installation is broken, results in Segmentation Fault [Core Dumped]

### ISSUE THREAD

**Issue by theo-michel** [deepmind/lab2d#28]
When trying to install and run lab2d on Ubuntu 18.04 and 22.04, both install, result in a segfault when running the env.step() in random_agent.py for example.

I was able to fix this by going back to an old [commit](https://github.com/deepmind/lab2d/commit/94e37d189aee8d309bc1dfae7227676c77636e88).

This is most likely due to a lot of the last changes that have been since May 18th to the installation files in order to make it work on mac OS.

**Comment by tkoeppe** [comment]
Oh, do you have any details on what goes wrong? Which kind of Lua are you using? Are you building from source, or using the wheels in the preview release?

And can you pinpoint the breaking commit? Candidates I would check are https://github.com/deepmind/lab2d/commit/247a9f6f5c4b9ca8a8dc0aad3db12b2c59c491b1 and https://github.com/deepmind/lab2d/commit/3a6a23b2d52651f1409550785a4651df001d1c9f.

(Note that the precommit checks on GitHub with Ubuntu 22.04 are passing.)

**Comment by tkoeppe** [comment]
For the time being, could you try building the luajit version with `--luajit_external_unwinder=false`?

**Comment by tkoeppe** [comment]
The breakage comes from my removal of the linker flag `-ulj_err_unwind_dwarf"` here: https://github.com/deepmind/lab2d/commit/3a6a23b2d52651f1409550785a4651df001d1c9f#diff-974bda3ce088dfb94cb46f06e6088f8c1d292e18331c511efcf3c79a2f2a30ceL175-L181

Without this flag, when the linker flag `-Wl,--gc-sections` is in use (which is implied by `-c opt`), and when using the GOLD linker, the symbol in question is erroneously considered unused and removed. By contrast, the LLD linker (which we use on the GitHub action runners) does not have this problem.

I recommend installing the LLD linker. If that's not an option, you can reinstate the above linker flag in `bazel/luajit.BUILD`. Alternatively you can also use the internal unwinder as I describe above.

**Comment by tkoeppe** [comment]
Fixed by https://github.com/deepmind/lab2d/commit/320b5f493dd69699c8a90090c225c41bef13dbf7, thanks for reporting!
