### ISSUE TITLE
WSL pip wheel installation issue on ubuntu 18.04

### ISSUE THREAD

**Issue by elliottower** [deepmind/lab2d#30]
I'm assuming the issue is something to do with the manylinux wheel being for a newer version of ubuntu, but I've never had issues installing any other software before so maybe it's possible to make it compatible?

`dmlab2d-1.0-cp310-cp310-manylinux_2_35_x86_64.whl is not a supported wheel on this platform.`

Also I see there are pypi wheels now, but it doesn't seem to work currently:
```pip install dmlab2d
ERROR: Could not find a version that satisfies the requirement dmlab2d
ERROR: No matching distribution found for dmlab2d
```

**Comment by jagapiou** [comment]
Yeah we build the wheel on ubuntu 22.04, we should build it on 20.04 so that Ubuntu 20.04 is supported.

Ubuntu 18 can't be supported I'm afraid as GitHub doesn't provide runners. (Note Ubuntu 18 is out of standard support now).

**Comment by tkoeppe** [comment]
I take it Ubuntu 18 uses glibc 2.27 or somethng like that? That's too old for our 2.35 wheel, indeed.

You could probably build your own wheel on an Ubuntu 18 machine, though.

**Comment by elliottower** [comment]
> Yeah we build the wheel on ubuntu 22.04, we should build it on 20.04 so that Ubuntu 20.04 is supported.
> 
> Ubuntu 18 can't be supported I'm afraid as GitHub doesn't provide runners. (Note Ubuntu 18 is out of standard support now).

Makes sense, I'll update my local installation then, mainly wanted to point out in case others have the same issue

**Comment by tkoeppe** [comment]
I don't think we can do anything to support older glibc's at this point. I believe the code is sufficiently portable that it shouldn't be hard to build it from source on older systems. But within the existing, supported GitHub infrastructure I don't think we can offer support for such end-of-life systems.

**Comment by elliottower** [comment]
Makes sense, no worries.
