### ISSUE TITLE
No instructions for building dmlab2d from source

### ISSUE THREAD

**Issue by DJayalath** [deepmind/lab2d#33]
The README.md at https://github.com/deepmind/meltingpot instructs users to check the README.md in this repository for details on installing dmlab2d from source if there is no appropriate wheel on PyPi. There are no instructions given in this README.

Previously, I was able to install dmlab2d via the `./install-dmlab2d.sh` script in previous editions of MeltingPot. This no longer works, giving a series of errors:
```
ERROR: /home/dhj26/.cache/bazel/_bazel_dhj26/2e165e68acd8599382bee991110c23fb/external/luajit_archive/BUILD.bazel:281:10: Middleman _middlemen/@luajit_Uarchive_S_S_Cbuildvm-BazelCppSemantics_build_arch_k8-opt-exec-2B5CBBC6 failed: missing input file '@luajit_archive//:src/luajit.h'
ERROR: /home/dhj26/.cache/bazel/_bazel_dhj26/2e165e68acd8599382bee991110c23fb/external/luajit_archive/BUILD.bazel:281:10: Middleman _middlemen/@luajit_Uarchive_S_S_Cbuildvm-BazelCppSemantics_build_arch_k8-opt-exec-2B5CBBC6 failed: 1 input file(s) do not exist
Target //dmlab2d:dmlab2d_wheel failed to build
ERROR: /home/dhj26/.cache/bazel/_bazel_dhj26/2e165e68acd8599382bee991110c23fb/external/luajit_archive/BUILD.bazel:281:10 Middleman _middlemen/@luajit_Uarchive_S_S_Cbuildvm-BazelCppSemantics_build_arch_k8-opt-exec-2B5CBBC6 failed: 1 input file(s) do not exist
INFO: Elapsed time: 247.903s, Critical Path: 2.92s
INFO: 182 processes: 29 internal, 153 linux-sandbox.
FAILED: Build did NOT complete successfully
```
I assume this is expected as that install script is no longer in the latest version of the repository.

Please could you provide a new solution for installing dmlab2d from source.

**Comment by tkoeppe** [comment]
Indeed, it looks like we don't provide instructions for building the wheel. Part of this is because I haven't uploaded the latest version of the readme yet, but we're also missing the instructions to build from source. @charlesbeattie, @jagapiou would you care to update our README (and I'll push the new version)?

As for the breakage, we recently changed the default build to use LuaJit instead of Lua 5.1. You can change that back by passing [`--lua_version=lua5_1`](https://github.com/deepmind/lab2d/blob/7fd7348da7e025a01e38878aa1bf17a3ce5836e0/.bazelrc#L13C14-L13C34) to the `bazel build` command. Alternatively, you could install LuaJit on your build machine.

**Comment by jagapiou** [comment]
Currently we have (pending) in the README:
```
`dmlab2d` is distributed as pre-built wheels for Linux and macOS. If there is no
appropriate wheel for your platform, you will need to build it from source. See
[`install.sh`](install.sh) for an example installation script that can be
adapted to your setup.
```
`install.sh` should also become public on the next copybara push.

I think that will suffice? Written instructions on how to install will basically just replicate `install.sh`.

**Comment by dimonenka** [comment]
Would it also be possible to use dmlab2d on Windows by building an appropriate wheel?

**Comment by tkoeppe** [comment]
@dimonenka: that's entirely untested, though in principle all the third-party libraries look like they should be pretty portable. I expect you'll have to tweak a few things, but it's worth giving it a try. You'll need a Windows build of bazel to get started.

**Comment by jagapiou** [comment]
The `install.sh` script is now available, I think this issue is now resolved?

**Comment by tkoeppe** [comment]
Thanks, @jagapiou!

**Comment by fardinsaad** [comment]
Can we build the dmlab2d on Windows? I am facing some difficulties building it on Windows! I have installed the Windows version of Bazel and tweaked the WORKSPACE and .bazelrc but couldn't get it to build.

**Comment by tkoeppe** [comment]
We have not worked on a Windows build, so the immediate answer is "no". That said, dmlab2d generally uses portable programming techniques and should in principle be buildable on Windows, you just need to set it up. Bazel works on Windows, too, I think. If you give it a try, stick with Lua 5.1 or 5.2 (not LuaJit).

The main issue I see is that some of the build rules (esp. around Python extensions) make some assumptions about compiler flags, so you might need to adjust those.

If someone donates a Windows dev machine, we could take a look :-)

**Comment by jzleibo** [comment]
I believe that one of the participants in the meltingpot challenge last
year was able to get it running on Windows. If you haven't solved this in a
couple days then ping me again and I'll try and find out who they were to
connect you with them
