### ISSUE TITLE
Lua "unknown directive" errors when building on Mac OS

### ISSUE THREAD

**Issue by RacingTadpole** [deepmind/lab2d#4]
Hi,

Thanks for helping me with #3!

I am still having problems building this with `bazel run -c opt dmlab2d/python:random_agent -- --level_name=clean_up` on mac OS unfortunately. I have updated both `WORKSPACE` and `python.BUILD` but I now get lots of errors like this:

```
bazel-out/darwin-opt/bin/external/luajit_archive/lj_vm.S:6:2: error: unknown directive
 .hidden lj_vm_asm_begin
 ^
bazel-out/darwin-opt/bin/external/luajit_archive/lj_vm.S:7:2: error: unknown directive
 .type lj_vm_asm_begin, @object
 ^
...
bazel-out/darwin-opt/bin/external/luajit_archive/lj_vm.S:2595:11: error:
mach-o section specifier uses an unknown section type
 .section .eh_frame,"a",@progbits
          ^
Target //dmlab2d/python:random_agent failed to build
```

Oddly I occasionally get this error instead (which is strange since Python.h is definitely in the place pointed to by WORKSPACE's `new_local_repository.path`):

```
In file included from dmlab2d/python/dmlab2d.cc:31:
In file included from external/pybind11_archive/include/pybind11/cast.h:13:
In file included from external/pybind11_archive/include/pybind11/pytypes.h:12:
external/pybind11_archive/include/pybind11/detail/common.h:124:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^~~~~~~~~~
1 error generated.
Target //dmlab2d/python:random_agent failed to build
```

Can you help? I've never used Bazel or lua before so I am hoping I'm just missing something obvious. 

Thanks!

**Comment by tkoeppe** [comment]
You're most welcome :-)

We don't have a build setup for LuaJit on MacOS at the moment (patches welcome!). So please use either `--config=lua5_1` or `--config=lua5_2` on MacOS.

To get Python to work you need to set the headers in `bazel/python.BUILD` according to your system. E.g. check what I did for the GitHub action runner in https://github.com/deepmind/lab2d/commit/f6b8774035a47e49f9e74dc9439b80266f2ee0e5#diff-05facd54dc227d5ba65b60508aee3b8ea42a3a715cbfec5a3f60b0493d40c3d5, and also check the precommit.yml file for a way to locate those files using `find`, https://github.com/deepmind/lab2d/commit/f6b8774035a47e49f9e74dc9439b80266f2ee0e5#diff-a0de7c6cf38c88f29e8556428f7bb036adc761202e6acaeb3ef0e83383012fbb.

**Comment by RacingTadpole** [comment]
Excellent, thanks - I wasn't sure where to put that (adding to the end of the `bazel run` command didn't seem to have any effect) but I changed `lua/BUILD` so the deps read
```
    deps = select({
        "//conditions:default": ["@lua5_2_archive//:lua5_2"],
        ":luajit": ["@luajit_archive//:luajit"],
```
and that led to a `Fetching @lua5_2_archive; fetching`, so that's looking good.

However I am now always getting the `'Python.h' file not found` error, always at `pybind11/detail/common.h:124:10`. Thanks for those links to the github runner, I tried changing both WORKSPACE and python.BUILD to refer to
```usr/local/Frameworks/Python.framework/Versions/3.8/Headers```
and also tried
```Library/Frameworks/Python.framework/Versions/3.8/Headers```
but unfortunately still the same error. (On my computer the headers are present at `/Library/Frameworks/...`).

**Comment by tkoeppe** [comment]
Something like `bazel build --config=lua5_1 //...` should work, similarly for `bazel run --config=lua5_1`. You can of course also edit the `BUILD` file as you have (or indeed add the default config in `.bazelrc`).

**Comment by tkoeppe** [comment]
The paths in the "external" BUILD files (such as `bazel/python.BUILD`) are _relative_ to the root path for that external tree given in `WORKSPACE`. So if `WORKSPACE` says the root path is `/usr`, then a path in`BUILD` file like `include/foo` refers to `/usr/include/foo`.

Make sure that you both add the actual files to the `python_headers` library via the glob in `hdrs`, and also that you specify the appropriate search path via the `include` field.

Here's a simple example, just to show everything in one piece:

**WORKSPACE:**

```
new_local_repository(
    name = "foo_lib",
    build_file = "@//bazel/foo.BUILD",
    path = "/usr",
)
```

**bazel/foo.BUILD:**

```
cc_library(
    name = "foo",
    hdrs = glob(["include/my_special_code/foo/*.h"]),
    include = ["include/my_special_code"],
)
```

Now a binary that depends on `@foo_lib//:foo_headers` and is compiled with, say, GCC, will receive the search path argument `-I/usr/include/my_special_code`, so that it can refer to the headers via `<foo/widget.h>` etc. The `/usr` bit comes from the `WORKSPACE`, and the `include/my_special_code` bit from the `:foo_headers` library target. For example:

**/src/some_code.cc:**
```c++
#include <foo/widget.h>
//...
```

**/src/BUILD:**

```
cc_binary(
    name = "some_code",
    srcs = ["some_code.cc"],
    deps = ["@foo_lib//:foo_headers"],
)
```

**Comment by RacingTadpole** [comment]
Amazing - that's got it working - thanks so much for explaining it so well!

For the record, I put this into `WORKSPACE`:
```
new_local_repository(
    name = "python_system",
    build_file = "@//bazel:python.BUILD",
    path = "/Library/Frameworks/Python.framework/Versions",
)
```

and this into `python.BUILD`:
```
cc_library(
    name = "python_headers",
    hdrs = select(
        {
            "@bazel_tools//tools/python:PY2": glob(["python2.7/*.h"]),
            "@bazel_tools//tools/python:PY3": glob(["3.8/Headers/**/*.h"]),
        },
        no_match_error = "Internal error, Python version should be one of PY2 or PY3",
    ),
    includes = select(
        {
            "@bazel_tools//tools/python:PY2": ["python2.7"],
            "@bazel_tools//tools/python:PY3": ["3.8/Headers"],
        },
        no_match_error = "Internal error, Python version should be one of PY2 or PY3",
    ),
    visibility = ["//visibility:public"],
)
```
(I didn't bother about fixing the python 2.7 paths.)
