### ISSUE TITLE
How do I run the trained agent, or play as a human?

### ISSUE THREAD

**Issue by RacingTadpole** [deepmind/lab2d#6]
Hi,

I'm excited to be able to start trying out lab2d now - can I ask a few questions about how to use it?

1. My understanding from the ["lab" docs](https://github.com/deepmind/lab#train-an-agent) is that when I run `bazel run dmlab2d/python:random_agent -- --level_name=clean_up` I am training an (initially random) agent in the "clean_up" world. What corresponds to the number of training steps in Fig 2 of [your paper](https://arxiv.org/pdf/2011.07027.pdf)? How do I run the trained agent?
2. The [clean_up/play.py](https://github.com/deepmind/lab2d/blob/main/dmlab2d/game_scripts/levels/clean_up/play.py) file starts with the comment "A simple human player for testing the `clean_up` level." How can I access the human player? The [lab docs](https://github.com/deepmind/lab#play-as-a-human) suggests something like `bazel run :game -- --level_script=tests/empty_room_test"` but I can't work out how to modify that for lab2d. 

(Two minor comments - is the difference between `level_script` and `level_name` significant? And all the different levels' `play.py` files start with comments saying they are for the "clean_up" level.)

Also, I imagine the training would go faster without the pygame rendering - can it be turned off during training?

Thanks!

Btw, I've had some fun watching the agent play the chase-eat level, `bazel run --config=lua5_2 dmlab2d/python:random_agent -- --level_name=chase_eat --num_episodes 100` 👻

**Comment by tkoeppe** [comment]
1. The "random agent" doesn't learn anything. It just takes random moves. It just demonstrates how to connect an agent and shows off (a part of) a given level.

2. The DeepMind Lab :game binary is something very Quake-III-specific and doesn't apply here, it's essentially a direct Quake-III UI (not an RL agent at all) that entirely bypasses the RL interface and serves mostly for direct testing of the levels. Here, in Lab 2D, we need to use a proper "human agent". I'm not sure about how to do this (I think it involves https://github.com/deepmind/lab2d/blob/main/dmlab2d/python/ui_renderer.py), @charlesbeattie should know this.

And indeed, in a real training setup you wouldn't render anything and drive it entirely headlessly.

**Comment by tkoeppe** [comment]
Oh, maybe it's something like `bazel run -c opt //dmlab2d/game_scripts/levels/chase_eat:play`?

**Comment by RacingTadpole** [comment]
Oh cool thanks - that `:play` command does try to compile but then hits a new arm64 problem 😢 
```
external/luajit_archive/src/host/buildvm.c:63:10: fatal error: '../dynasm/dasm_arm64.h' file not found
#include "../dynasm/dasm_arm64.h"
```

So - putting that aside - how do I go about training a model in lab2d?

**Comment by tkoeppe** [comment]
Yes, as discussed before, you probably need `--define=lua=lua5_1` or somesuch, since luajit doesn't work for ARM.

**Comment by RacingTadpole** [comment]
d'oh! sorry, yes that's got it, thanks!
```
bazel run -c opt --config=lua5_2 //dmlab2d/game_scripts/levels/chase_eat:play
```

**Comment by tkoeppe** [comment]
Training an agent is the essence of RL research, isn't it :-) That's not in scope for Lab 2D, which only provides the environment. You need to build your own learning agent, with whatever technology you like.

**Comment by tkoeppe** [comment]
Please reopen if you want to discuss anything else.
