### ISSUE TITLE
Readme example on how to run random_agent needs to be updated

### ISSUE THREAD

**Issue by jifflund** [deepmind/lab2d#8]
I think the Readme.md example on how to run random_agent using bazel needs to be updated since the python.BUILD was removed in a recent commit.  

I corrected this in a branch but don't have permission to push the branch to this repo, so pushed that branch here: https://github.com/jifflund/lab2d/tree/readme_fix
The specific correction is made on line 31, see https://github.com/jifflund/lab2d/blob/readme_fix/README.md#getting-started. Note, I also added  --config=lua5_2  to the example to make it easier for Mac users to run it.

**Comment by tkoeppe** [comment]
If you create a proper "fork" (in the GitHub terminology), you could send a "pull request" for your change so we could easily merge it. But if it's OK with you I could just make the change directly? (Then you wouldn't be credited in the author line, though.)

**Comment by tkoeppe** [comment]
If it's just about changing `dmlab2d/python:` to `dmlab2d:`, I'd be happy to do that directly, if you don't mind not being the commit author?

**Comment by jifflund** [comment]
Thanks @tkoeppe  for the suggestions.  I opened a pull request from a forked branch to make sure I did it right for future PRs.  If it's easier, feel free to make the change directly in main.

Separately, I'm planning to add in a hidden_rewards value from the step method into lab2d/dm_env/meltingpot to enable safety/control/ethics research.  I'll open a separate issue for that thread.

**Comment by charlesbeattie** [comment]
I would recommend adding a new observation for hidden rewards. We often don't use reward returned from step and use rewards placed in observations instead. See https://github.com/deepmind/lab2d/blob/f634c378d428dd19e8b154aa5b590d33f42438bf/dmlab2d/lib/game_scripts/levels/clean_up/avatar.lua#L182 for an example.

**Comment by jifflund** [comment]
@charlesbeattie , 👍  Thanks for the reference.   I added a comment to the other issue on the hidden_rewards and closed that other one.  https://github.com/deepmind/lab2d/issues/10

**Comment by jifflund** [comment]
Code was fixed and merged to main so closing issue.
